package com.thewinterframework.processor;

import com.thewinterframework.processor.wire.ClassListWire;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import javax.tools.ToolProvider;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ExternalComponentProcessingTest {

	@TempDir
	Path temporaryDirectory;

	@Test
	void installsExternalComponentsIntoAConsumer() throws Exception {
		final var producerOutput = temporaryDirectory.resolve("producer-output");
		final var producerSource = writeSource(
				"producer/external/SharedComponent.java",
				"""
				package external;

				import com.thewinterframework.component.annotation.Component;
				import com.thewinterframework.component.annotation.ComponentScope;

				@Component(scope = ComponentScope.EXTERNAL)
				public final class SharedComponent {}
				"""
		);
		assertEquals(0, compile(producerOutput, List.of(producerSource), System.getProperty("java.class.path")));

		final var index = producerOutput.resolve("META-INF/winter/components.index");
		assertTrue(Files.readString(index).contains("component:external.SharedComponent"));

		final var consumerOutput = temporaryDirectory.resolve("consumer-output");
		final var consumerSource = writeSource(
				"consumer/consumer/ConsumerPlugin.java",
				"""
				package consumer;

				import com.thewinterframework.plugin.WinterBootPlugin;

				@WinterBootPlugin
				public final class ConsumerPlugin {}
				"""
		);
		final var originalLoader = Thread.currentThread().getContextClassLoader();
		try (final var producerLoader = new URLClassLoader(new java.net.URL[]{producerOutput.toUri().toURL()}, originalLoader)) {
			Thread.currentThread().setContextClassLoader(producerLoader);
			final var classPath = System.getProperty("java.class.path")
					+ System.getProperty("path.separator")
					+ producerOutput;
			assertEquals(0, compile(consumerOutput, List.of(consumerSource), classPath));
		} finally {
			Thread.currentThread().setContextClassLoader(originalLoader);
		}

		assertTrue(Files.exists(consumerOutput.resolve(
				"consumer/autogenerated_winter_modules/ComponentListWire.class"
		)));
		assertTrue(Files.exists(consumerOutput.resolve(
				"consumer/autogenerated_winter_modules/ProcessorModuleProvider.class"
		)));
		try (final var runtimeLoader = new URLClassLoader(
				new java.net.URL[]{consumerOutput.toUri().toURL(), producerOutput.toUri().toURL()},
				getClass().getClassLoader()
		)) {
			final var wireType = runtimeLoader.loadClass("consumer.autogenerated_winter_modules.ComponentListWire");
			final var wire = (ClassListWire) wireType.getDeclaredConstructor().newInstance();
			assertEquals(
					List.of("external.SharedComponent"),
					wire.getWiredClasses().stream().map(Class::getName).toList()
			);
			final var moduleWireType = runtimeLoader.loadClass(
					"consumer.autogenerated_winter_modules.ProcessorModuleProvider"
			);
			final var moduleWire = (ClassListWire) moduleWireType.getDeclaredConstructor().newInstance();
			assertTrue(moduleWire.getWiredClasses().stream()
					.anyMatch(type -> type.getName().equals("com.thewinterframework.component.ComponentModule")));
		}
	}

	private Path writeSource(final String relativePath, final String source) throws Exception {
		final var path = temporaryDirectory.resolve(relativePath);
		Files.createDirectories(path.getParent());
		Files.writeString(path, source, StandardCharsets.UTF_8);
		return path;
	}

	private int compile(final Path output, final List<Path> sources, final String classPath) throws Exception {
		Files.createDirectories(output);
		final var compiler = ToolProvider.getSystemJavaCompiler();
		try (final var files = compiler.getStandardFileManager(null, null, StandardCharsets.UTF_8)) {
			final var compilationUnits = files.getJavaFileObjectsFromPaths(sources);
			final var task = compiler.getTask(
					null,
					files,
					null,
					List.of("-classpath", classPath, "-d", output.toString(), "-parameters"),
					null,
					compilationUnits
			);
			task.setProcessors(List.of(new WinterProcessor()));
			return Boolean.TRUE.equals(task.call()) ? 0 : 1;
		}
	}
}
