package com.thewinterframework.processor;

import com.google.auto.service.AutoService;
import com.thewinterframework.plugin.WinterBootPlugin;
import com.thewinterframework.plugin.WinterPlugin;
import com.thewinterframework.processor.context.ProcessorContext;
import com.thewinterframework.processor.handler.WinterAnnotationProcessor;
import com.thewinterframework.processor.template.TemplateBuilder;
import com.thewinterframework.processor.wire.ClassListWire;
import com.thewinterframework.utils.reflect.ProcessorUtils;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

@AutoService(javax.annotation.processing.Processor.class)
public class WinterProcessor extends AbstractProcessor {

	public static final String AUTOGENERATED_PACKAGE = "autogenerated_winter_modules";

	private List<WinterAnnotationProcessor> handlers;
	private Map<String, List<WinterAnnotationProcessor>> handlersByAnnotation;
	private final Set<String> wiredClasses = new HashSet<>();

	private Element pluginClass;

	private List<WinterAnnotationProcessor> loadHandlers() {
		final var loader = ServiceLoader.load(WinterAnnotationProcessor.class, WinterAnnotationProcessor.class.getClassLoader());
		return StreamSupport.stream(loader.spliterator(), false).collect(Collectors.toList());
	}

	private Element loadPluginClass(final RoundEnvironment roundEnv) {
		if (this.pluginClass == null) {
			this.pluginClass = getPluginClass(roundEnv, processingEnv);
		}

		return this.pluginClass;
	}

	public static Element getPluginClass(final RoundEnvironment roundEnv, final ProcessingEnvironment processingEnv) {
		return roundEnv.getElementsAnnotatedWith(
				processingEnv
						.getElementUtils()
						.getTypeElement(WinterBootPlugin.class.getCanonicalName())
		).stream().findFirst().orElse(null);
	}

	@Override
	public synchronized void init(final ProcessingEnvironment env) {
		super.init(env);

		if (ProcessorUtils.getProjectType(env) == ProcessorUtils.ProjectType.API) {
			return;
		}

		this.handlers = loadHandlers();
		this.handlers.forEach(h -> h.onInit(env));

		this.handlersByAnnotation = new HashMap<>();

		for (final var handler : this.handlers) {
			for (final var ann : handler.getSupportedAnnotations()) {
				this.handlersByAnnotation.computeIfAbsent(ann.getCanonicalName(), k -> new ArrayList<>())
						.add(handler);
			}
		}
	}

	@Override
	public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
		if (ProcessorUtils.getProjectType(processingEnv) == ProcessorUtils.ProjectType.API) {
			return false;
		}

		if (loadPluginClass(roundEnv) == null) {
			processingEnv.getMessager().printError(WinterBootPlugin.class.getCanonicalName() + " annotation not found in project!");
			return false;
		}

		final var ctx = new ProcessorContext(processingEnv, pluginClass, roundEnv);
		handlers.forEach(h -> h.onRoundStart(ctx));

		for (final var annotation : annotations) {
			if (annotation.getQualifiedName().toString().equals(WinterBootPlugin.class.getCanonicalName())) {
				continue;
			}

			final var list = handlersByAnnotation.get(annotation.getQualifiedName().toString());
			if (list == null) {
				processingEnv.getMessager().printWarning(annotation.getQualifiedName().toString() + " annotation has no registered handlers!");
				continue;
			}

			final var elements = roundEnv.getElementsAnnotatedWith(annotation);
			for (final var handler : list) {
				handler.handle(annotation, elements, ctx);
			}
		}

		handlers.forEach(h -> h.onRoundEnd(ctx));
		wiredClasses.addAll(ctx.getRequiredModulesAsClasses());

		if (roundEnv.processingOver()) {
			handlers.forEach(h -> h.onProcessingComplete(ctx));
			generateModules(ctx);
		}

		return true;
	}

	void generateModules(final ProcessorContext ctx) {
		final var packageName = ctx.getWinterModulePackageString();
		final var className = "ProcessorModuleProvider";

		writeClassWire(ctx, className, packageName, wiredClasses);
	}

	@Override
	public Set<String> getSupportedAnnotationTypes() {
		final var supportedAnnotations = loadHandlers().stream()
				.flatMap(handler -> handler.getSupportedAnnotations().stream())
				.map(Class::getCanonicalName)
				.collect(Collectors.toCollection(HashSet::new));

		supportedAnnotations.add(WinterBootPlugin.class.getCanonicalName());
		return supportedAnnotations;
	}

	@Override
	public SourceVersion getSupportedSourceVersion() {
		return SourceVersion.latestSupported();
	}

	public static void writeClassWire(final ProcessorContext context, final String className, final String packageName, final Iterable<String> wiredClasses) {
		TemplateBuilder.fromResource("generated/ClassListWireTemplate.java")
				.placeholder("PACKAGE_NAME", packageName)
				.placeholder("CLASS_NAME", className)
				.placeholder("WIRED_CLASSES", String.join(", ", wiredClasses))
				.write(context, context.getWinterModuleQualifiedNameStringFor(className));
	}

	public static String autogeneratedWinterPluginPackage(final WinterPlugin plugin) {
		return plugin.getClass().getPackageName() + "." + WinterProcessor.AUTOGENERATED_PACKAGE;
	}

	public static String autoGeneratedProcessorModuleProviderCanonicalName(final WinterPlugin plugin) {
		return plugin.getClass().getPackageName() + "." + WinterProcessor.AUTOGENERATED_PACKAGE + ".ProcessorModuleProvider";
	}

	public static ClassListWire getModuleProvider(final WinterPlugin plugin) throws Exception {
		final var moduleProviderCanonicalClass = autoGeneratedProcessorModuleProviderCanonicalName(plugin);
		final var moduleProviderClass = Class.forName(moduleProviderCanonicalClass);
		return (ClassListWire) moduleProviderClass.getConstructors()[0].newInstance();
	}

}
