package com.thewinterframework.processor;

import com.google.auto.service.AutoService;
import com.thewinterframework.plugin.WinterBootPlugin;
import com.thewinterframework.plugin.WinterPlugin;
import com.thewinterframework.processor.context.ProcessorContext;
import com.thewinterframework.processor.component.ComponentMetadataProcessor;
import com.thewinterframework.processor.handler.WinterAnnotationProcessor;
import com.thewinterframework.processor.extension.WinterProcessorExtension;
import com.thewinterframework.processor.template.TemplateBuilder;
import com.thewinterframework.processor.wire.ClassListWire;
import com.thewinterframework.utils.reflect.ProcessorUtils;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import java.util.*;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

@AutoService(javax.annotation.processing.Processor.class)
public class WinterProcessor extends AbstractProcessor {

	public static final String AUTOGENERATED_PACKAGE = "autogenerated_winter_modules";

	private List<WinterProcessorExtension> handlers;
	private Map<String, List<WinterProcessorExtension>> handlersByAnnotation;
	private final Set<String> wiredClasses = new HashSet<>();
	private final ComponentMetadataProcessor componentProcessor = new ComponentMetadataProcessor();

	private Element pluginClass;

	private List<WinterProcessorExtension> loadHandlers() {
		final var classLoader = WinterProcessor.class.getClassLoader();
		final var extensions = StreamSupport.stream(
				ServiceLoader.load(WinterProcessorExtension.class, classLoader).spliterator(),
				false
		);
		final var legacy = StreamSupport.stream(
				ServiceLoader.load(WinterAnnotationProcessor.class, classLoader).spliterator(),
				false
		);
		final var unique = new LinkedHashMap<Class<?>, WinterProcessorExtension>();
		Stream.concat(extensions, legacy)
				.sorted(Comparator.comparingInt(WinterProcessorExtension::order).thenComparing(handler -> handler.getClass().getName()))
				.forEach(handler -> unique.putIfAbsent(handler.getClass(), handler));
		return List.copyOf(unique.values());
	}

	private Element loadPluginClass(final RoundEnvironment roundEnv) {
		if (this.pluginClass == null) {
			this.pluginClass = getPluginClass(roundEnv, processingEnv);
		}

		return this.pluginClass;
	}

	public static Element getPluginClass(final RoundEnvironment roundEnv, final ProcessingEnvironment processingEnv) {
		return roundEnv.getElementsAnnotatedWith(
				processingEnv
						.getElementUtils()
						.getTypeElement(WinterBootPlugin.class.getCanonicalName())
		).stream().findFirst().orElse(null);
	}

	@Override
	public synchronized void init(final ProcessingEnvironment env) {
		super.init(env);

		if (ProcessorUtils.getProjectType(env) == ProcessorUtils.ProjectType.API) {
			return;
		}

		this.handlers = loadHandlers();
		this.handlers.forEach(h -> h.initialize(env));

		this.handlersByAnnotation = new HashMap<>();

		for (final var handler : this.handlers) {
			for (final var annotationName : handler.supportedAnnotationNames()) {
				this.handlersByAnnotation.computeIfAbsent(annotationName, k -> new ArrayList<>())
						.add(handler);
			}
		}
	}

	@Override
	public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
		if (ProcessorUtils.getProjectType(processingEnv) == ProcessorUtils.ProjectType.API) {
			return false;
		}

		componentProcessor.scan(processingEnv, roundEnv);
		if (loadPluginClass(roundEnv) == null) {
			if (roundEnv.processingOver()) {
				componentProcessor.finishLibrary(processingEnv);
			}
			return false;
		}

		final var ctx = new ProcessorContext(processingEnv, pluginClass, roundEnv);
		handlers.forEach(h -> h.onRoundStarted(ctx));

		for (final var annotation : annotations) {
			if (annotation.getQualifiedName().toString().equals(WinterBootPlugin.class.getCanonicalName())) {
				continue;
			}

			final var list = handlersByAnnotation.get(annotation.getQualifiedName().toString());
			if (list == null) {
				continue;
			}

			final var elements = roundEnv.getElementsAnnotatedWith(annotation);
			for (final var handler : list) {
				handler.process(annotation, elements, ctx);
			}
		}

		handlers.forEach(h -> h.onRoundFinished(ctx));
		wiredClasses.addAll(ctx.getRequiredModulesAsClasses());

		if (roundEnv.processingOver()) {
			handlers.forEach(h -> h.onProcessingFinished(ctx));
			componentProcessor.finishPlugin(ctx);
			wiredClasses.addAll(ctx.getRequiredModulesAsClasses());
			generateModules(ctx);
		}

		return false;
	}

	void generateModules(final ProcessorContext ctx) {
		final var packageName = ctx.getWinterModulePackageString();
		final var className = "ProcessorModuleProvider";

		writeClassWire(ctx, className, packageName, wiredClasses.stream().sorted().toList());
	}

	@Override
	public Set<String> getSupportedAnnotationTypes() {
		return Set.of("*");
	}

	@Override
	public SourceVersion getSupportedSourceVersion() {
		return SourceVersion.latestSupported();
	}

	public static void writeClassWire(final ProcessorContext context, final String className, final String packageName, final Iterable<String> wiredClasses) {
		TemplateBuilder.fromResource("generated/ClassListWireTemplate.java")
				.placeholder("PACKAGE_NAME", packageName)
				.placeholder("CLASS_NAME", className)
				.placeholder("WIRED_CLASSES", String.join(", ", wiredClasses))
				.write(context, context.getWinterModuleQualifiedNameStringFor(className));
	}

	public static String autogeneratedWinterPluginPackage(final WinterPlugin plugin) {
		return plugin.getClass().getPackageName() + "." + WinterProcessor.AUTOGENERATED_PACKAGE;
	}

	public static String autoGeneratedProcessorModuleProviderCanonicalName(final WinterPlugin plugin) {
		return plugin.getClass().getPackageName() + "." + WinterProcessor.AUTOGENERATED_PACKAGE + ".ProcessorModuleProvider";
	}

	public static ClassListWire getModuleProvider(final WinterPlugin plugin) throws Exception {
		final var moduleProviderCanonicalClass = autoGeneratedProcessorModuleProviderCanonicalName(plugin);
		final var moduleProviderClass = Class.forName(moduleProviderCanonicalClass, true, plugin.getClass().getClassLoader());
		return (ClassListWire) moduleProviderClass.getConstructors()[0].newInstance();
	}

}
