package com.thewinterframework.service;

import com.google.inject.Binder;
import com.google.inject.Scopes;
import com.thewinterframework.plugin.WinterPlugin;
import com.thewinterframework.plugin.module.PluginModule;
import com.thewinterframework.processor.provider.AutoGeneratedClassListProvider;
import com.thewinterframework.service.annotation.Service;

/**
 * Module for services.
 * <p> This module scans for classes annotated with {@link Service} and binds them to the injector. </p>
 */
public class ServiceModule implements PluginModule {

	private final ServiceManager serviceManager = new ServiceManager();

	@Override
	public void configure(Binder binder) {
		binder.bindScope(Service.class, Scopes.SINGLETON);
		binder.bind(ServiceManager.class).toInstance(serviceManager);
		binder.bind(ReloadServiceManager.class).in(Scopes.SINGLETON);
	}

	@Override
	public boolean onLoad(WinterPlugin plugin) {
		final var start = System.currentTimeMillis();

		try {
			final var classListProvider = AutoGeneratedClassListProvider.scan(plugin.getClass(), Service.class);
			for (final var service : classListProvider.getClassList()) {
				serviceManager.registerService(service);
			}
		} catch (Exception e) {
			plugin.getSLF4JLogger().error("Failed to scan services", e);
			return false;
		}

		serviceManager.loadHandlers(plugin);
		plugin.getSLF4JLogger().info("Loaded {} services in {}ms", serviceManager.services().size(), System.currentTimeMillis() - start);
		return true;
	}

	@Override
	public boolean onEnable(WinterPlugin plugin) {
		final var start = System.currentTimeMillis();
		serviceManager.startHandlers(plugin);
		plugin.getSLF4JLogger().info("Enabled {} services in {}ms", serviceManager.services().size(), System.currentTimeMillis() - start);
		return true;
	}

	@Override
	public boolean onDisable(WinterPlugin plugin) {
		final var start = System.currentTimeMillis();
		serviceManager.stopHandlers(plugin);
		plugin.getSLF4JLogger().info("Disabled {} services in {}ms", serviceManager.services().size(), System.currentTimeMillis() - start);
		return true;
	}
}
