package com.thewinterframework.processor.context;

import com.thewinterframework.processor.WinterProcessor;
import com.thewinterframework.processor.module.ProcessorModule;

import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.PackageElement;
import javax.lang.model.util.Elements;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

public class ProcessorContext {

	private final ProcessingEnvironment env;
	private final Element pluginClass;
	private final RoundEnvironment roundEnv;

	private final Set<String> requiredModules = new HashSet<>();

	public ProcessorContext(
			final ProcessingEnvironment env,
			final Element pluginClass,
			final RoundEnvironment roundEnv
	) {
		this.env = env;
		this.pluginClass = pluginClass;
		this.roundEnv = roundEnv;
	}

	public RoundEnvironment roundEnv() {
		return roundEnv;
	}

	public Filer filer() {
		return env.getFiler();
	}

	public Elements elements() {
		return env.getElementUtils();
	}

	public Messager messager() {
		return env.getMessager();
	}

	public PackageElement getPluginPackage() {
		return elements().getPackageOf(pluginClass);
	}

	public String getPluginPackageString() {
		return getPluginPackage().getQualifiedName().toString();
	}

	public String getWinterModulePackageString() {
		return getPluginPackageString() + "." + WinterProcessor.AUTOGENERATED_PACKAGE;
	}

	public String getWinterModuleQualifiedNameStringFor(final String className) {
		return getWinterModulePackageString() + "." + className;
	}

	public String getWinterModuleQualifiedNameStringFor(final Class<?> clazz) {
		return getWinterModulePackageString() + "." + clazz.getSimpleName();
	}

	public void wireModule(final Class<? extends ProcessorModule> module) {
		requiredModules.add(module.getCanonicalName());
	}

	public void wireModule(final String module) {
		requiredModules.add(module);
	}

	public Set<String> getRequiredModules() {
		return requiredModules;
	}

	public Set<String> getRequiredModulesAsClasses() {
		return requiredModules.stream()
				.map(module -> module + ".class")
				.collect(Collectors.toSet());
	}
}
