package com.thewinterframework.processor.clazz;

import com.thewinterframework.plugin.WinterPlugin;
import com.thewinterframework.processor.WinterProcessor;
import com.thewinterframework.processor.context.ProcessorContext;
import com.thewinterframework.processor.handler.WinterAnnotationProcessor;

import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import java.lang.annotation.Annotation;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

public abstract class ClassWireProcessor implements WinterAnnotationProcessor {

	private final Collection<String> classes = new HashSet<>();

	protected ProcessingEnvironment env;

	@Override
	public void onInit(final ProcessingEnvironment env) {
		this.env = env;
	}

	@Override
	public final Set<Class<? extends Annotation>> getSupportedAnnotations() {
		return Set.of(wiredAnnotation());
	}

	public static String wiredClassName(final Class<? extends Annotation> annotation) {
		return annotation.getSimpleName() + "ListWire";
	}

	public static String canonicalWiredClassName(final WinterPlugin plugin, final Class<? extends Annotation> annotation) {
		return WinterProcessor.autogeneratedWinterPluginPackage(plugin) + "." + wiredClassName(annotation);
	}

	protected abstract Class<? extends Annotation> wiredAnnotation();

	protected boolean filter(final TypeElement annotation, final Element element, final ProcessorContext ctx) {
		return true;
	}

	@Override
	public void handle(final TypeElement annotation, final Set<? extends Element> elements, final ProcessorContext ctx) {
		for (final var e : elements) {
			if (e.getKind() != ElementKind.CLASS) continue;
			if (!filter(annotation, e, ctx)) continue;
			classes.add(e.asType().toString() + ".class");
		}
	}

	@Override
	public void onProcessingComplete(final ProcessorContext ctx) {
		final var className = wiredClassName(wiredAnnotation());
		final var packageName = ctx.getWinterModulePackageString();
		WinterProcessor.writeClassWire(ctx, className, packageName, classes);
	}
}