package com.thewinterframework.paper.yaml.processor;

import com.google.auto.service.AutoService;
import com.thewinterframework.paper.yaml.FileName;
import com.thewinterframework.processor.context.ProcessorContext;
import com.thewinterframework.processor.handler.WinterAnnotationProcessor;
import com.thewinterframework.processor.template.TemplateBuilder;

import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import java.lang.annotation.Annotation;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@AutoService(WinterAnnotationProcessor.class)
public class YamlConfigProcessor implements WinterAnnotationProcessor {

	private static final Pattern ELEMENT_PATTERN = Pattern.compile("(?:<el>)([\\s\\S]*?)(?:<\\/el>)");

	@Override
	public Set<Class<? extends Annotation>> getSupportedAnnotations() {
		return Set.of(FileName.class);
	}

	@Override
	public void handle(final TypeElement annotation, final Set<? extends Element> elements, final ProcessorContext ctx) {
		final var fields = elements.stream()
				.filter(e -> e.getKind() == ElementKind.FIELD || e.getKind() == ElementKind.PARAMETER)
				.map(e -> (VariableElement) e)
				.collect(Collectors.toSet());

		if (fields.isEmpty()) {
			return;
		}

		final var pkg = ctx.getWinterModulePackageString() + ".autogenerated_winter_config_module";
		final var className = "YamlConfigModule";

		TemplateBuilder.fromResource("generated/AutoGeneratedYamlConfigModule.java")
				.placeholder("PACKAGE_NAME", pkg)
				.placeholder("CLASS_NAME", className)
				.custom(content -> {
					final var matcher = ELEMENT_PATTERN.matcher(content);
					final var result = new StringBuilder();
					final var alreadyWritten = new HashSet<String>();
					var lastEnd = 0;

					while (matcher.find()) {
						result.append(content, lastEnd, matcher.start());

						final var block = matcher.group(1);
						final var builder = new StringBuilder();

						for (final var field : fields) {
							final var ann = field.getAnnotation(FileName.class);
							if (ann == null || !alreadyWritten.add(ann.value())) continue;

							builder.append(block
									.replace("<FILE_NAME>", ann.value())
									.replace("<NAME>", field.getSimpleName().toString())
							).append(System.lineSeparator());
						}

						result.append(builder);
						lastEnd = matcher.end();
					}
					result.append(content.substring(lastEnd));
					return result.toString();
				})
				.write(ctx, pkg + "." + className);

		ctx.wireModule(pkg + "." + className);
	}
}